### ISSUE TITLE
Add many to many through relation for sponsors

### ISSUE THREAD

**Issue by Gandi24** [meetpy/meetpy#13]
Each sponsor can sponsor different things for different meetups. Sponsor description is one thing, we should enable adding a comment about what they're sponsoring at specific meetup.

**Comment by artcz** [comment]
Given that the Sponsor's description could also be slightly different between the meetups, maybe we should put that description in the relation as well? (and make it default to the main Sponsor.description)

Same idea applies to Speaker bios.

**Comment by gbdlin** [comment]
This should also allow reordering sponsors in a specific meetup, as sometimes one sponsor is more important than other ones and should be on top.
