### ISSUE TITLE
Option to post new proposals to slack or send them via email

### ISSUE THREAD

**Issue by artcz** [meetpy/meetpy#20]
When we get a new proposal on the website we should get some alert either on slack or on a mailing list somewhere, so that it's easier to notice. ;)

**Comment by gbdlin** [comment]
Add discord to that too (webhook should be enough).

**Comment by gbdlin** [comment]
Mail alerts were already implemented from the beginning, they just needed fixing mail server settings.

Slack is out of scope now, as we've moved to Discord.
