### ISSUE TITLE
Version display in footer contains unnecessary b''

### ISSUE THREAD

**Issue by Gandi24** [meetpy/meetpy#8]
![image](https://user-images.githubusercontent.com/747721/45188498-dc5e2100-b234-11e8-8d19-5f15bc05a902.png)

Courtesy of https://pythonlodz.org/ :)

**Comment by Gandi24** [comment]
PR: https://github.com/meetpy/meetpy/pull/15

**Comment by MattBlack85** [comment]
#15 fixed this, can be closed
